language: node_js
node_js:
- node
deploy:
  provider: npm
  email: alex@apollonet.fr
  api_key: admSf/mmfKdctUAZ24w1rXpb6XowYYZg9508d34wLTm41EJ6xnPKh1tHi4hBo5QiOLxxdjzemKS9cwgEJtZURQuZhR+NW4v4JXVXXApdnQfNeN8p51bw5894lw3u91rJScJS6Vhe4oHiA8KWS9+gK4ZJKwqrTj7K0bHtozqtkNwu05JC1aXrEkXMpCXcap51/lLnqslqTWUVqtkGgoZEZC8gpM6vs28wjw0p9Dh0n/FxyjgDsgxWoqOMAf86ojQH6nqMj0nMoH7MI1JSUo5umNwrR3aVxm7Lzo1Psn0YiBfYBTZ/th9z/VEPHiEZlEdc4wUOK0rzCvGNTxP7qkTSxNqSxAi/tuqifDL4Xda0XQy5kykSKsP+fb0Ntfs0fsvaWLE7g6ppPHx8kpoFaY3YswjKSjXgez9wk7rbNhTWyUnHI5WpI7pT1jNkJ5cOU70iQfGW+rDjU96nKiXCiOLPBpCI/Cic65+OjvKnmYJ5x0bpMBaN12wEVbrPX9o5kM2fxnWoBRRNVDs3WRh/gAF15H4JeRR+pPm7G0934isECkVDIsiH2ntv04o8ZrynYqhJ7hzDRSNLvRD8X1tGcVo+vcLpDKL2TIMWa8YgbADUQNWmozwzqbH94ICJIm5gECTrFU9DbV0zt+QlMUWQji5cYf2o2Aicwy3NvBcZhKP+OXI=
